In [ ]:
import numpy as np 
array_unidimensional = np.array([1,2,3,4,5])
array_unidimensional

In [4]:
lista = [1,2,3,4,5]
def media(lista):
    soma = sum(lista)
    media = soma / len(lista)
    return media

print(media(lista))

3.0


In [14]:
lista = [10,-20,30,40,50,-3,7,8]
positivos = []
negativos = []

def separar(lista):
    for x in lista:
        if x > 0:
            positivos.append(x)
        else:
            negativos.append(x)
    print(f'Positivos: {positivos}')
    print(f'Negativos: {negativos}')

separar(lista)

Positivos: [10, 30, 40, 50, 7, 8]
Negativos: [-20, -3]


In [15]:
#Calcule a soma dos quadrados de uma lista

lista = [10,30,40,50,7,8]
soma = 0

def quadradoSoma(lista):
    resultado = 0
    for x in lista:
        resultado += (x * x)
    return(resultado)

soma = quadradoSoma(lista)
print(f'A soma dos quadrados da lista é {soma}')

A soma dos quadrados da lista é 5213


In [18]:
import pandas as pd

In [46]:
dados = pd.read_csv('manutencao_preditiva.csv')
dados

UDI ID Produto Tipo  Temperatura Ar [K]  Temperatura Processo [K]  \
0         1     M14860    M               298.1                     308.6   
1         2     L47181    L               298.2                     308.7   
2         3     L47182    L               298.1                     308.5   
3         4     L47183    L               298.2                     308.6   
4         5     L47184    L               298.2                     308.7   
...     ...        ...  ...                 ...                       ...   
9995   9996     M24855    M               298.8                     308.4   
9996   9997     H39410    H               298.9                     308.4   
9997   9998     M24857    M               299.0                     308.6   
9998   9999     H39412    H               299.0                     308.7   
9999  10000     M24859    M               299.0                     308.7   

      Velocidade Rotacao [rpm]  Torque [Nm]  Desgaste Ferramenta [min]  Alvo  \
0                         1551         42.8                          0     0   
1                         1408         46.3                          3     0   
2                         1498         49.4                          5     0   
3                         1433         39.5                          7     0   
4                         1408         40.0                          9     0   
...                        ...          ...                        ...   ...   
9995                      1604         29.5                         14     0   
9996                      1632         31.8                         17     0   
9997                      1645         33.4                         22     0   
9998                      1408         48.5                         25     0   
9999                      1500         40.2                         30     0   

     Tipo da Falha  
0       No Failure  
1       No Failure  
2       No Failure  
3       No Failure  
4       No Failure  
...            ...  
9995    No Failure  
9996    No Failure  
9997    No Failure  
9998    No Failure  
9999    No Failure  

[10000 rows x 10 columns]

In [48]:
dados_selec = dados[['Temperatura Processo [K]', 'Velocidade Rotacao [rpm]']]

cinco_linhas = dados_selec.head(5)
cinco_linhas

matriz = cinco_linhas.values
matriz

array([[ 308.6, 1551. ],
       [ 308.7, 1408. ],
       [ 308.5, 1498. ],
       [ 308.6, 1433. ],
       [ 308.7, 1408. ]])

In [49]:
import numpy as np

In [50]:
soma_elementos = np.sum(matriz)

print(soma_elementos)

8841.1


In [53]:
min_elementos = np.min(matriz)
max_elementos = np.max(matriz)
print(f'Minimo: {min_elementos}')
print(f'Máximo: {max_elementos}')

Minimo: 308.5
Máximo: 1551.0


In [55]:
media1 = np.mean(matriz, axis = 0)
media2 = np.mean(matriz, axis = 1)
print(media1)
print(media2)

[ 308.62 1459.6 ]
[929.8  858.35 903.25 870.8  858.35]


In [57]:
transpor = np.transpose(matriz)
print(transpor)

[[ 308.6  308.7  308.5  308.6  308.7]
 [1551.  1408.  1498.  1433.  1408. ]]


In [59]:
print(matriz)

[[ 308.6 1551. ]
 [ 308.7 1408. ]
 [ 308.5 1498. ]
 [ 308.6 1433. ]
 [ 308.7 1408. ]]
